### ISSUE TITLE
Interactive display without homeassistant using TTGO buttons

### ISSUE THREAD

**Issue by pacc** [pulimento/TTGO-T-Display-esphome-homeassistant-sample#2]
I'm just leaving my code here since I wanted to try out the TTGO display without any other dependencies.

Without homeassistant or attached sensors it would be nice to use the buttons on the TTGO to test out functionality,
Here is my attempt to update the display using predefined pages when clicking on a button:

```
esphome:
  name: ttgo

esp32:
  board: ttgo-lora32-v1
  framework:
    type: arduino

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    id: tdisplay_button_input_1
    on_click:
     - display.page.show: page2
     - component.update: my_display

  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    id: tdisplay_button_input_0
    on_click:
     - display.page.show: page1
     - component.update: my_display

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO TDisplay 135x240
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    id: my_display 
    pages:
      - id: page0        
        lambda: |-
          it.print(0, 10, id(roboto), "Hello!");
      - id: page1
        lambda: |-
          it.print(0, 10, id(roboto), "Button 1!");
      - id: page2
        lambda: |-
          it.print(0, 10, id(roboto), "Button 2!");
```
The pages can of course contain live data as define in this repository.
Define some passwords and fallback hotspot to use it in your wifi network with esphome functionality.
