### ISSUE TITLE
ttg.yaml does not build (anymore)

### ISSUE THREAD

**Issue by lecrams** [pulimento/TTGO-T-Display-esphome-homeassistant-sample#3]
After the update to esphome V2023-12 the example ttg.yaml does not build anymore. I get the following error:
![image](https://github.com/pulimento/TTGO-T-Display-esphome-sample/assets/74721082/32630fd9-7b79-4eeb-96fb-f774287d73bd)

**Comment by Nokius** [comment]
The issue can be resolved with `allow_other_uses: True` with in the pin section. see below 
```
- platform: gpio      # Long press button 0
    pin: 
      number: GPIO0
      allow_other_uses: True
      inverted: True
    name: "Long Press Button 0"
    id: long_press_button_0
    on_click: 
      min_length: 1001ms
      max_length: 5000ms
      then:
        - switch.toggle: backlight_switch
```
